### ISSUE TITLE
[FEAT] 코드 리팩토링, 코드 주석 생성 기능 화면 구성 및 API 연결

### ISSUE THREAD

**Issue by Largopie** [Team-Dasom/co-re-websites#44]
## ISSUE

- 코드 리팩토링 기능 화면 구성, API 연결
- 코드 주석 생성 기능 화면 구성, API 연결
## TODO

- [x] 코드 리팩토링 기능 화면 구성
- [x] 코드 리팩토링 기능 API 연결
- [x] 코드 주석 생성 기능 화면 구성
- [x] 코드 주석 생성 기능 API 연결
