### ISSUE TITLE
[UI] 필요한 부분 UI 개선

### ISSUE THREAD

**Issue by Largopie** [Team-Dasom/co-re-websites#51]
## ISSUE
- 필요한 부분 UI 개선

## TODO
- [x] 코드 입력 부분 길이가 길어지면 크기가 크기가 늘어난 후 submit 보내게 되면 다시 작아지지 않는 부분 수정
- [x] 채팅창 부드럽게 올라올 수 있도록 구현
- [x] 채팅을 기다리는 동안 로딩 화면 구현
