### ISSUE TITLE
[ADD] GPT 바로가기

### ISSUE THREAD

**Issue by hijiyun** [Team-Dasom/co-re-websites#58]
## ISSUE

- 헤더에 GPT아이콘 삽입
- 아이콘 클릭 시 GPT페이지로 바로가기
- hover속성으로 누르면 어떻게 되는지 간략하게 소개
 
## TODO

- [x] 헤더에 GPT아이콘 삽입
- [x] 아이콘 클릭 시 GPT페이지로 바로가기
- [x] hover속성으로 누르면 어떻게 되는지 간략하게 소개
