### ISSUE TITLE
[FEAT] 로그아웃 구현

### ISSUE THREAD

**Issue by hijiyun** [Team-Dasom/co-re-websites#61]
## ISSUE

- 로그아웃 구현

## TODO

- [x] 로그아웃 버튼 구현
- [x] 쿠키에서 이미지 및 닉네임 지우기
- [x] 메인 페이지로 이동
