### ISSUE TITLE
[UI] 대화내용 즐겨찾기 기능 추가

### ISSUE THREAD

**Issue by hijiyun** [Team-Dasom/co-re-websites#77]
## ISSUE

-  대화내용 즐겨찾기 버튼 추가
-  대화내용 쓰레기통 버튼 추가
- 버튼 위치 조정

## TODO

- [x] 대화내용 즐겨찾기 버튼 추가
- [x] 대화내용 쓰레기통 버튼 추가
- [x] 버튼 위치 조정
